//*****************************************************************************
//*****************************************************************************
//  FILENAME: Counter24.h
//   Version: 2.5, Updated on 2015/3/4 at 22:23:45
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Counter24 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Counter24_INCLUDE
#define Counter24_INCLUDE

#include <m8c.h>

#pragma fastcall16 Counter24_EnableInt
#pragma fastcall16 Counter24_DisableInt
#pragma fastcall16 Counter24_Start
#pragma fastcall16 Counter24_Stop
#pragma fastcall16 Counter24_ReadCounter              // Read  DR0
#pragma fastcall16 Counter24_WritePeriod              // Write DR1
#pragma fastcall16 Counter24_ReadCompareValue         // Read  DR2
#pragma fastcall16 Counter24_WriteCompareValue        // Write DR2


//-------------------------------------------------
// Prototypes of the Counter24 API.
//-------------------------------------------------
                                                                           
extern void Counter24_EnableInt(void);                           // Proxy Class 1
extern void Counter24_DisableInt(void);                          // Proxy Class 1
extern void Counter24_Start(void);                               // Proxy Class 1
extern void Counter24_Stop(void);                                // Proxy Class 1
extern void Counter24_ReadCounter(DWORD * pdwCount);             // Proxy Class 3
extern void Counter24_WritePeriod(DWORD dwPeriod);               // Proxy Class 2
extern void Counter24_ReadCompareValue(DWORD * pdwCompareValue); // Proxy Class 3
extern void Counter24_WriteCompareValue(DWORD dwCompareValue);   // Proxy Class 2


//--------------------------------------------------
// Constants for Counter24 API's.
//--------------------------------------------------

#define Counter24_CONTROL_REG_START_BIT        ( 0x01 )
#define Counter24_INT_REG_ADDR                 ( 0x0e1 )
#define Counter24_INT_MASK                     ( 0x04 )


//--------------------------------------------------
// Constants for Counter24 user defined values
//--------------------------------------------------

#define Counter24_PERIOD                       ( 0x7a120 )
#define Counter24_COMPARE_VALUE                ( 0x0 )


//-------------------------------------------------
// Register Addresses for Counter24
//-------------------------------------------------

#pragma ioport  Counter24_COUNTER_LSB_REG:  0x020          //Count register LSB
BYTE            Counter24_COUNTER_LSB_REG;
#pragma ioport  Counter24_COUNTER_ISB_REG:  0x024          //Count register ISB
BYTE            Counter24_COUNTER_ISB_REG;
#pragma ioport  Counter24_COUNTER_MSB_REG:  0x028          //Count register MSB
BYTE            Counter24_COUNTER_MSB_REG;
#pragma ioport  Counter24_PERIOD_LSB_REG:   0x021          //Period register LSB
BYTE            Counter24_PERIOD_LSB_REG;
#pragma ioport  Counter24_PERIOD_ISB_REG:   0x025          //Period register ISB
BYTE            Counter24_PERIOD_ISB_REG;
#pragma ioport  Counter24_PERIOD_MSB_REG:   0x029          //Period register MSB
BYTE            Counter24_PERIOD_MSB_REG;
#pragma ioport  Counter24_COMPARE_LSB_REG:  0x022          //Compare register LSB
BYTE            Counter24_COMPARE_LSB_REG;
#pragma ioport  Counter24_COMPARE_ISB_REG:  0x026          //Compare register ISB
BYTE            Counter24_COMPARE_ISB_REG;
#pragma ioport  Counter24_COMPARE_MSB_REG:  0x02a          //Compare register MSB
BYTE            Counter24_COMPARE_MSB_REG;
#pragma ioport  Counter24_CONTROL_LSB_REG:  0x023          //Control register LSB
BYTE            Counter24_CONTROL_LSB_REG;
#pragma ioport  Counter24_CONTROL_ISB_REG:  0x027          //Control register ISB
BYTE            Counter24_CONTROL_ISB_REG;
#pragma ioport  Counter24_CONTROL_MSB_REG:  0x02b          //Control register MSB
BYTE            Counter24_CONTROL_MSB_REG;
#pragma ioport  Counter24_FUNC_LSB_REG: 0x120              //Function register LSB
BYTE            Counter24_FUNC_LSB_REG;
#pragma ioport  Counter24_FUNC_ISB_REG: 0x124              //Function register ISB
BYTE            Counter24_FUNC_ISB_REG;
#pragma ioport  Counter24_FUNC_MSB_REG: 0x128              //Function register MSB
BYTE            Counter24_FUNC_MSB_REG;
#pragma ioport  Counter24_INPUT_LSB_REG:    0x121          //Input register LSB
BYTE            Counter24_INPUT_LSB_REG;
#pragma ioport  Counter24_INPUT_ISB_REG:    0x125          //Input register ISB
BYTE            Counter24_INPUT_ISB_REG;
#pragma ioport  Counter24_INPUT_MSB_REG:    0x129          //Input register MSB
BYTE            Counter24_INPUT_MSB_REG;
#pragma ioport  Counter24_OUTPUT_LSB_REG:   0x122          //Output register LSB
BYTE            Counter24_OUTPUT_LSB_REG;
#pragma ioport  Counter24_OUTPUT_ISB_REG:   0x126          //Output register ISB
BYTE            Counter24_OUTPUT_ISB_REG;
#pragma ioport  Counter24_OUTPUT_MSB_REG:   0x12a          //Output register MSB
BYTE            Counter24_OUTPUT_MSB_REG;
#pragma ioport  Counter24_INT_REG:       0x0e1             //Interrupt Mask Register
BYTE            Counter24_INT_REG;


//-------------------------------------------------
// Counter24 Macro 'Functions'
//-------------------------------------------------

#define Counter24_Start_M \
   ( Counter24_CONTROL_LSB_REG |=  Counter24_CONTROL_REG_START_BIT )

#define Counter24_Stop_M  \
   ( Counter24_CONTROL_LSB_REG &= ~Counter24_CONTROL_REG_START_BIT )

#define Counter24_EnableInt_M   \
   M8C_EnableIntMask(  Counter24_INT_REG, Counter24_INT_MASK )

#define Counter24_DisableInt_M  \
   M8C_DisableIntMask( Counter24_INT_REG, Counter24_INT_MASK )

#endif
// end of file Counter24.h
