//*****************************************************************************
//*****************************************************************************
//  FILENAME: Timer24.h
//   Version: 2.6, Updated on 2015/3/4 at 22:27:47
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Timer24 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Timer24_INCLUDE
#define Timer24_INCLUDE

#include <m8c.h>

#pragma fastcall16 Timer24_EnableInt
#pragma fastcall16 Timer24_DisableInt
#pragma fastcall16 Timer24_Start
#pragma fastcall16 Timer24_Stop
#pragma fastcall16 Timer24_ReadTimer                // Read  DR0
#pragma fastcall16 Timer24_ReadTimerSaveCV          // Read  DR0
#pragma fastcall16 Timer24_WritePeriod              // Write DR1
#pragma fastcall16 Timer24_ReadCompareValue         // Read  DR2
#pragma fastcall16 Timer24_WriteCompareValue        // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 Timer24_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 Timer24_CaptureCounter           // Read  DR0 "Obsolete"


//-------------------------------------------------
// Prototypes of the Timer24 API.
//-------------------------------------------------

extern void Timer24_EnableInt(void);                                    // Proxy  1
extern void Timer24_DisableInt(void);                                   // Proxy  1
extern void Timer24_Start(void);                                        // Proxy  1
extern void Timer24_Stop(void);                                         // Proxy  1
extern void Timer24_ReadTimer(DWORD * pdwCount);                        // Proxy  3
extern void Timer24_ReadTimerSaveCV(DWORD * pdwCount);                  // Proxy  3
extern void Timer24_WritePeriod(DWORD dwPeriod);                        // Proxy  2
extern void Timer24_ReadCompareValue(DWORD * pdwCompareValue);          // Proxy  3
extern void Timer24_WriteCompareValue(DWORD dwCompareValue);            // Proxy  2

// The following functions are deprecated.
// They may be omitted in future releases
//
extern void Timer24_ReadCounter(DWORD * pdwCount);          // Obsolete
extern void Timer24_CaptureCounter(DWORD * pdwCount);       // Obsolete


//--------------------------------------------------
// Constants for Timer24 API's.
//--------------------------------------------------

#define Timer24_CONTROL_REG_START_BIT          ( 0x01 )
#define Timer24_INT_REG_ADDR                   ( 0x0e1 )
#define Timer24_INT_MASK                       ( 0x04 )


//--------------------------------------------------
// Constants for Timer24 user defined values
//--------------------------------------------------

#define Timer24_PERIOD                         ( 0x0 )
#define Timer24_COMPARE_VALUE                  ( 0x0 )


//-------------------------------------------------
// Register Addresses for Timer24
//-------------------------------------------------

#pragma ioport  Timer24_COUNTER_LSB_REG:    0x020          //Count register LSB
BYTE            Timer24_COUNTER_LSB_REG;
#pragma ioport  Timer24_COUNTER_ISB_REG:    0x024          //Count register ISB
BYTE            Timer24_COUNTER_ISB_REG;
#pragma ioport  Timer24_COUNTER_MSB_REG:    0x028          //Count register MSB
BYTE            Timer24_COUNTER_MSB_REG;
#pragma ioport  Timer24_PERIOD_LSB_REG: 0x021              //Period register LSB
BYTE            Timer24_PERIOD_LSB_REG;
#pragma ioport  Timer24_PERIOD_ISB_REG: 0x025              //Period register ISB
BYTE            Timer24_PERIOD_ISB_REG;
#pragma ioport  Timer24_PERIOD_MSB_REG: 0x029              //Period register MSB
BYTE            Timer24_PERIOD_MSB_REG;
#pragma ioport  Timer24_COMPARE_LSB_REG:    0x022          //Compare register LSB
BYTE            Timer24_COMPARE_LSB_REG;
#pragma ioport  Timer24_COMPARE_ISB_REG:    0x026          //Compare register ISB
BYTE            Timer24_COMPARE_ISB_REG;
#pragma ioport  Timer24_COMPARE_MSB_REG:    0x02a          //Compare register MSB
BYTE            Timer24_COMPARE_MSB_REG;
#pragma ioport  Timer24_CONTROL_LSB_REG:    0x023          //Control register LSB
BYTE            Timer24_CONTROL_LSB_REG;
#pragma ioport  Timer24_CONTROL_ISB_REG:    0x027          //Control register ISB
BYTE            Timer24_CONTROL_ISB_REG;
#pragma ioport  Timer24_CONTROL_MSB_REG:    0x02b          //Control register MSB
BYTE            Timer24_CONTROL_MSB_REG;
#pragma ioport  Timer24_FUNC_LSB_REG:   0x120              //Function register LSB
BYTE            Timer24_FUNC_LSB_REG;
#pragma ioport  Timer24_FUNC_ISB_REG:   0x124              //Function register ISB
BYTE            Timer24_FUNC_ISB_REG;
#pragma ioport  Timer24_FUNC_MSB_REG:   0x128              //Function register MSB
BYTE            Timer24_FUNC_MSB_REG;
#pragma ioport  Timer24_INPUT_LSB_REG:  0x121              //Input register LSB
BYTE            Timer24_INPUT_LSB_REG;
#pragma ioport  Timer24_INPUT_ISB_REG:  0x125              //Input register ISB
BYTE            Timer24_INPUT_ISB_REG;
#pragma ioport  Timer24_INPUT_MSB_REG:  0x129              //Input register MSB
BYTE            Timer24_INPUT_MSB_REG;
#pragma ioport  Timer24_OUTPUT_LSB_REG: 0x122              //Output register LSB
BYTE            Timer24_OUTPUT_LSB_REG;
#pragma ioport  Timer24_OUTPUT_ISB_REG: 0x126              //Output register ISB
BYTE            Timer24_OUTPUT_ISB_REG;
#pragma ioport  Timer24_OUTPUT_MSB_REG: 0x12a              //Output register MSB
BYTE            Timer24_OUTPUT_MSB_REG;
#pragma ioport  Timer24_INT_REG:       0x0e1               //Interrupt Mask Register
BYTE            Timer24_INT_REG;


//-------------------------------------------------
// Timer24 Macro 'Functions'
//-------------------------------------------------

#define Timer24_Start_M \
   ( Timer24_CONTROL_LSB_REG |=  Timer24_CONTROL_REG_START_BIT )

#define Timer24_Stop_M  \
   ( Timer24_CONTROL_LSB_REG &= ~Timer24_CONTROL_REG_START_BIT )

#define Timer24_EnableInt_M   \
   M8C_EnableIntMask(  Timer24_INT_REG, Timer24_INT_MASK )

#define Timer24_DisableInt_M  \
   M8C_DisableIntMask( Timer24_INT_REG, Timer24_INT_MASK )

#endif
// end of file Timer24.h
